// This file was autogenerated by C:\Users\andre_000\_Work_\repos\Github\gremlinjs\node_modules\mantri\lib/../node_modules/closure-tools/closure-bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('.tmp/scripts/gremlin/Application.js', ['gremlin.Application'], ['gremlin.conf.Configuration', 'gremlin.domObserver.DomObserver', 'gremlin.gremlins.GremlinCollection']);
goog.addDependency('.tmp/scripts/gremlin/conf/Configuration.js', ['gremlin.conf.Configuration'], ['gremlin.event.Event', 'gremlin.util.Helper']);
goog.addDependency('.tmp/scripts/gremlin/domObserver/Clocks/ClockFactory.js', ['gremlin.domObserver.clocks.ClockFactory'], ['gremlin.domObserver.clocks.CssAnimationClock', 'gremlin.domObserver.clocks.LegacyTimeoutClock', 'gremlin.domObserver.clocks.MutationObserverClock', 'gremlin.util.FeatureDetector']);
goog.addDependency('.tmp/scripts/gremlin/domObserver/Clocks/CssAnimationClock.js', ['gremlin.domObserver.clocks.CssAnimationClock'], ['gremlin.domObserver.clocks.cssAnimationStyle', 'gremlin.util.Helper']);
goog.addDependency('.tmp/scripts/gremlin/domObserver/Clocks/CssAnimationStyle.js', ['gremlin.domObserver.clocks.cssAnimationStyle'], ['gremlin.gremlins.NameProvider']);
goog.addDependency('.tmp/scripts/gremlin/domObserver/Clocks/LegacyTimeoutClock.js', ['gremlin.domObserver.clocks.LegacyTimeoutClock'], []);
goog.addDependency('.tmp/scripts/gremlin/domObserver/Clocks/MutationObserverClock.js', ['gremlin.domObserver.clocks.MutationObserverClock'], []);
goog.addDependency('.tmp/scripts/gremlin/domObserver/DomObserver.js', ['gremlin.domObserver.DomObserver'], ['gremlin.MutationObserverShim', 'gremlin.domObserver.ElementList', 'gremlin.util.Helper']);
goog.addDependency('.tmp/scripts/gremlin/domObserver/ElementList.js', ['gremlin.domObserver.ElementList'], ['gremlin.gremlins.NameProvider', 'gremlin.util.FeatureDetector']);
goog.addDependency('.tmp/scripts/gremlin/domObserver/MutationObserverShim.js', ['gremlin.MutationObserverShim'], ['gremlin.domObserver.clocks.ClockFactory', 'gremlin.event.Event']);
goog.addDependency('.tmp/scripts/gremlin/event/Event.js', ['gremlin.event.Event'], []);
goog.addDependency('.tmp/scripts/gremlin/gremlinDefinitions/AbstractGremlin.js', ['gremlin.gremlinDefinitions.AbstractGremlin'], []);
goog.addDependency('.tmp/scripts/gremlin/gremlinDefinitions/ExtensionRegistry.js', ['gremlin.gremlinDefinitions.ExtensionRegistry'], ['gremlin.gremlinDefinitions.AbstractGremlin']);
goog.addDependency('.tmp/scripts/gremlin/gremlinDefinitions/Pool.js', ['gremlin.gremlinDefinitions.Pool'], ['gremlin.gremlinDefinitions.AbstractGremlin', 'gremlin.util.Helper']);
goog.addDependency('.tmp/scripts/gremlin/gremlins/GremlinCollection.js', ['gremlin.gremlins.GremlinCollection'], ['gremlin.gremlins.GremlinDomElement', 'gremlin.gremlins.NameProvider']);
goog.addDependency('.tmp/scripts/gremlin/gremlins/GremlinDomElement.js', ['gremlin.gremlins.GremlinDomElement'], ['gremlin.gremlins.GremlinFactory', 'gremlin.util.ElementData.ElementData', 'gremlin.util.FeatureDetector', 'gremlin.util.Helper']);
goog.addDependency('.tmp/scripts/gremlin/gremlins/GremlinFactory.js', ['gremlin.gremlins.GremlinFactory'], ['gremlin.gremlinDefinitions.ExtensionRegistry', 'gremlin.gremlinDefinitions.Pool']);
goog.addDependency('.tmp/scripts/gremlin/gremlins/NameProvider.js', ['gremlin.gremlins.NameProvider'], ['gremlin.util.Helper']);
goog.addDependency('.tmp/scripts/gremlin/util/Debug.js', ['gremlin.util.Debug'], ['gremlin.util.Helper']);
goog.addDependency('.tmp/scripts/gremlin/util/ElementData/DataValue.js', ['gremlin.util.ElementData.DataValue'], []);
goog.addDependency('.tmp/scripts/gremlin/util/ElementData/ElementData.js', ['gremlin.util.ElementData.ElementData'], ['gremlin.util.ElementData.DataValue', 'gremlin.util.Helper']);
goog.addDependency('.tmp/scripts/gremlin/util/FeatureDetector.js', ['gremlin.util.FeatureDetector'], []);
goog.addDependency('.tmp/scripts/gremlin/util/Helper.js', ['gremlin.util.Helper'], []);
goog.addDependency('.tmp/scripts/gremlin/util/polyfill.js', ['gremlin.util.polyfill'], []);
goog.addDependency('.tmp/scripts/gremlin/util/ready.js', ['gremlin.util.ready'], []);
goog.addDependency('.tmp/scripts/gremlinjs.js', ['GremlinJS'], ['gremlin.Application', 'gremlin.conf.Configuration', 'gremlin.event.Event', 'gremlin.gremlinDefinitions.AbstractGremlin', 'gremlin.gremlinDefinitions.ExtensionRegistry', 'gremlin.gremlinDefinitions.Pool', 'gremlin.util.Debug', 'gremlin.util.Helper', 'gremlin.util.polyfill', 'gremlin.util.ready']);
