// Generated by CoffeeScript 1.6.3
(function() {
  window.AddTest = (function() {
    function AddTest() {
      AddTest.__super__.constructor.apply(this, arguments);
    }

    return AddTest;

  })();

}).call(this);

/*
//@ sourceMappingURL=AddTest.map
*/
