// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.CreateTest = (function(_super) {
    __extends(CreateTest, _super);

    function CreateTest() {
      CreateTest.__super__.constructor.apply(this, arguments);
      this.el.__gremlin = this;
    }

    return CreateTest;

  })(G.Gizmo);

}).call(this);

/*
//@ sourceMappingURL=CreateTest.map
*/
