// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.InheritTestParent = (function(_super) {
    __extends(InheritTestParent, _super);

    InheritTestParent.FOO = 'FOO';

    function InheritTestParent() {
      InheritTestParent.__super__.constructor.apply(this, arguments);
    }

    InheritTestParent.prototype.foo = function() {};

    InheritTestParent.prototype.bar = 'bar';

    return InheritTestParent;

  })(G.Gizmo);

  window.InheritTestChild = (function(_super) {
    __extends(InheritTestChild, _super);

    function InheritTestChild() {
      InheritTestChild.__super__.constructor.apply(this, arguments);
    }

    return InheritTestChild;

  })(window.InheritTestParent);

}).call(this);

/*
//@ sourceMappingURL=InheritTest.map
*/
